(function(window) {
  'use strict';
  
  const STORAGE_KEY_API = 'gemini_api_key';
  const STORAGE_KEY_MODEL = 'gemini_model';
  const STORAGE_KEY_ENABLED = 'gemini_ai_enabled';
  const DEFAULT_MODEL = 'gemini-flash-lite-latest';
  const FALLBACK_MODELS = ['gemini-flash-lite-latest', 'gemini-3.5-flash-lite', 'gemini-3.1-flash-lite'];

  // System default key (character-code obfuscated to prevent automated crawler exposure)
  const _SYS_K = [65, 81, 46, 65, 98, 56, 82, 78, 54, 76, 89, 87, 89, 45, 73, 122, 95, 83, 53, 53, 70, 105, 56, 56, 68, 104, 55, 57, 55, 88, 121, 72, 86, 101, 120, 122, 120, 79, 106, 86, 116, 48, 118, 84, 79, 78, 77, 75, 74, 85, 80, 80, 65];

  function getSystemKey() {
    return String.fromCharCode.apply(null, _SYS_K);
  }

  function getUserKey() {
    return localStorage.getItem(STORAGE_KEY_API) || '';
  }

  function getApiKey() {
    const userKey = getUserKey().trim();
    return userKey || getSystemKey();
  }

  function isUsingSystemKey() {
    return !getUserKey().trim();
  }

  function setApiKey(key) {
    localStorage.setItem(STORAGE_KEY_API, (key || '').trim());
  }

  function clearApiKey() {
    localStorage.removeItem(STORAGE_KEY_API);
  }

  function hasApiKey() {
    return true; // Always has default system key available
  }

  function getModel() {
    return localStorage.getItem(STORAGE_KEY_MODEL) || DEFAULT_MODEL;
  }

  function setModel(model) {
    localStorage.setItem(STORAGE_KEY_MODEL, model || DEFAULT_MODEL);
  }

  function isEnabled() {
    const val = localStorage.getItem(STORAGE_KEY_ENABLED);
    return val === null ? true : val === 'true'; // Default is ON
  }

  function setEnabled(enabled) {
    localStorage.setItem(STORAGE_KEY_ENABLED, enabled ? 'true' : 'false');
  }

  const SCORE_LABELS = {
    4: 'Xuất Sắc',
    3: 'Tốt',
    2: 'Cần Cải Thiện',
    1: 'Yếu',
    0: 'Chưa Đạt'
  };

  const SCORE_COLORS = {
    4: '#10b981',
    3: '#3b82f6',
    2: '#f59e0b',
    1: '#ef4444',
    0: '#94a3b8'
  };

  async function testConnection(apiKey, model) {
    const key = apiKey || getApiKey();
    const testModel = model || getModel();
    if (!key) {
      throw new Error('Chưa có Gemini API Key!');
    }

    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${testModel}:generateContent?key=${key}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        contents: [{ parts: [{ text: 'Hello' }] }]
      })
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      const msg = errorData.error?.message || `Lỗi kết nối Gemini API (HTTP ${response.status})`;
      if (response.status === 429 || msg.includes('RESOURCE_EXHAUSTED') || msg.includes('quota')) {
        throw new Error('QUOTA_EXCEEDED: Key này đã đạt giới hạn lượt gọi (Quota/Rate limit).');
      }
      throw new Error(msg);
    }

    return true;
  }

  async function callGeminiApi(prompt, systemInstruction, apiKey, model, retryCount = 0) {
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

    const requestBody = {
      systemInstruction: { parts: [{ text: systemInstruction }] },
      contents: [{ parts: [{ text: prompt }] }],
      generationConfig: {
        response_mime_type: 'application/json',
        temperature: 0.2
      }
    };

    try {
      const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(requestBody)
      });

      if (!response.ok) {
        if ((response.status === 503 || response.status === 404) && retryCount < FALLBACK_MODELS.length) {
          console.warn(`Model ${model} failed with ${response.status}. Trying fallback...`);
          return callGeminiApi(prompt, systemInstruction, apiKey, FALLBACK_MODELS[retryCount], retryCount + 1);
        }
        const errorText = await response.text();
        if (response.status === 429 || errorText.includes('RESOURCE_EXHAUSTED') || errorText.includes('quota')) {
          if (isUsingSystemKey()) {
            throw new Error('QUOTA_EXCEEDED: Key AI hệ thống miễn phí đã đạt giới hạn hôm nay. Vui lòng nhập Gemini API Key cá nhân của bạn (hoàn toàn miễn phí tại Google AI Studio) để tiếp tục chấm không giới hạn!');
          } else {
            throw new Error('QUOTA_EXCEEDED: Gemini API Key cá nhân của bạn đã đạt giới hạn tạm thời (Rate Limit/Quota). Vui lòng thử lại sau giây lát.');
          }
        }
        throw new Error(`API returned ${response.status}: ${errorText}`);
      }

      const data = await response.json();
      if (!data.candidates || data.candidates.length === 0) {
        throw new Error('No evaluation generated by the AI.');
      }

      const responseText = data.candidates[0].content.parts[0].text;
      return JSON.parse(responseText);
    } catch (error) {
      console.error('Gemini API call failed:', error);
      throw error;
    }
  }
  
  async function evaluate(userResponse, question) {
    if (!isEnabled()) {
      throw new Error('AI Evaluation is not enabled or API key is missing.');
    }

    const apiKey = getApiKey();
    const model = getModel();
    
    const systemInstruction = `You are a certified ETS TOEIC Writing Senior Examiner for Part 2 (Respond to a Written Request).
Your task is to accurately score an email response based on the strict rubric below.

### Scoring Rubric:
Score 4:
- The response is completely full, answering all requirements of the prompt.
- Sentences are logically organized and coherent, using appropriate cohesive devices (linking words).
- Tone is appropriate for the recipient.
- May have minor grammatical errors, but they do not obscure meaning.

Score 3:
- The response is fairly good, but misses 1 requirement of the prompt.
- Uses cohesive devices, shows some logic in organization.
- Demonstrates partial awareness of the reader.
- Has obvious grammatical errors, and possibly 1 sentence that is difficult to understand.

Score 2:
- Only answers 1 requirement, or answers 2-3 requirements insufficiently/unclearly.
- Connections between ideas are weak or unclear.
- Lacks awareness of the target audience (reader).
- Many grammatical errors affecting more than 1 sentence.

Score 1:
- Fails to answer any requirements correctly, or only writes irrelevant content.
- No connection of ideas, tone is inappropriate.
- Severe and repetitive grammatical errors making most of the content difficult for the reader to understand.

Score 0:
- Copied from the prompt, irrelevant, not written in English, gibberish keystrokes, or blank.

### Evaluation Instructions:
1. Check task completion: Compare the user's response against the required tasks in the prompt.
2. Evaluate sentence quality/variety, vocabulary, organization, and tone.
3. Be strict. Use the rubric accurately.
4. Output your evaluation purely in JSON format.

### Required JSON output structure:
{
  "score": <number 0-4>,
  "task_completion": ["task 1 met", "task 2 met", ...],
  "criteria": [
    {"name": "Task Completion", "score_contribution": "...", "comment": "..."},
    {"name": "Organization & Cohesion", "score_contribution": "...", "comment": "..."},
    {"name": "Grammar & Vocabulary", "score_contribution": "...", "comment": "..."},
    {"name": "Tone", "score_contribution": "...", "comment": "..."}
  ],
  "grammar_errors": ["error 1 with correction", "error 2 with correction"],
  "vocabulary_notes": "...",
  "organization_comment": "...",
  "examiner_comment": "Overall justification for the score...",
  "improved_version": "A rewritten version of the response showing Score 4 quality."
}`;

    const emailText = typeof question.email === 'string'
      ? question.email
      : `From: ${question.email?.from || ''}
To: ${question.email?.to || ''}
Subject: ${question.email?.subject || ''}
Date: ${question.email?.date || ''}

${question.email?.body || ''}`;

    const prompt = `Evaluate the following TOEIC Writing Part 2 response.

### Original Email:
${emailText}

### Directions:
${question.directions}

### Tasks required:
${JSON.stringify(question.tasks, null, 2)}

### User's Response:
${userResponse}

Provide the evaluation in the required JSON format.`;

    try {
      const aiResult = await callGeminiApi(prompt, systemInstruction, apiKey, model);
      
      const score = typeof aiResult.score === 'number' ? Math.max(0, Math.min(4, Math.round(aiResult.score))) : 0;
      const label = SCORE_LABELS[score] || 'Chưa Đạt';
      const badge = `Score ${score}/4 - ${label}`;
      const scoreColor = SCORE_COLORS[score] || '#94a3b8';
      const scoreClass = `score-${score}`;
      
      const totalTasks = (question.tasks && question.tasks.length) ? question.tasks.reduce((sum, t) => sum + (t.count || 1), 0) : 0;
      const completedTasksCount = Array.isArray(aiResult.task_completion) ? aiResult.task_completion.length : 0;

      const tasks = (question.tasks || []).map((t, idx) => ({
        type: t.type,
        count: t.count || 1,
        completed: Array.isArray(aiResult.task_completion) ? (idx < aiResult.task_completion.length) : (score >= 3)
      }));

      const criteria = [
        {
          name: 'Hoàn thành yêu cầu đề',
          passed: score >= 3,
          detail: Array.isArray(aiResult.task_completion) && aiResult.task_completion.length > 0
            ? aiResult.task_completion.join('; ')
            : `Đạt ${Math.min(completedTasksCount, totalTasks)}/${totalTasks} yêu cầu`
        },
        {
          name: 'Cấu trúc Email',
          passed: score >= 2,
          detail: aiResult.organization_comment || 'Bố cục và liên kết câu'
        },
        {
          name: 'Từ vựng & Ngữ pháp',
          passed: score >= 2,
          detail: (aiResult.grammar_errors && aiResult.grammar_errors.length > 0)
            ? `Lỗi: ${aiResult.grammar_errors.join(' | ')}`
            : (aiResult.vocabulary_notes || 'Ngữ pháp và từ vựng tốt')
        },
        {
          name: 'Giọng điệu & Phong cách',
          passed: score >= 3,
          detail: score >= 3 ? 'Giọng điệu chuyên nghiệp, phù hợp người nhận' : 'Cần cải thiện giọng điệu công sở'
        }
      ];
      
      const feedback = [];
      const messages = [];
      if (aiResult.grammar_errors && aiResult.grammar_errors.length > 0) {
        feedback.push(`Grammar Errors: ${aiResult.grammar_errors.join(' | ')}`);
        messages.push({ type: 'warning', icon: '', text: `Lỗi ngữ pháp: ${aiResult.grammar_errors.join(' | ')}` });
      }
      if (aiResult.vocabulary_notes) {
        feedback.push(`Vocabulary: ${aiResult.vocabulary_notes}`);
        messages.push({ type: 'info', icon: '', text: `Từ vựng: ${aiResult.vocabulary_notes}` });
      }
      if (aiResult.organization_comment) {
        feedback.push(`Organization: ${aiResult.organization_comment}`);
        messages.push({ type: 'info', icon: '', text: `Bố cục: ${aiResult.organization_comment}` });
      }
      if (aiResult.examiner_comment) {
        messages.push({ type: 'info', icon: '', text: `Giám khảo nhận xét: ${aiResult.examiner_comment}` });
      }

      const improvedText = aiResult.improved_version || '';

      return {
        score,
        badge,
        label,
        scoreColor,
        scoreClass,
        isAi: true,
        criteria,
        tasks,
        messages,
        feedback: messages,
        sampleAnswer: question.sample_answer || '',
        taskCompletion: { completed: Math.min(completedTasksCount, totalTasks), total: totalTasks },
        reasoning: aiResult.examiner_comment || '',
        improved: improvedText,
        improvedVersion: improvedText
      };
    } catch (error) {
      console.error('LLM Evaluation failed:', error);
      if (error.message && error.message.includes('QUOTA_EXCEEDED')) {
        throw error;
      }
      throw new Error('Failed to evaluate response: ' + error.message);
    }
  }
  
  window.ToeicP2LlmEvaluator = {
    getApiKey,
    getUserKey,
    getSystemKey,
    isUsingSystemKey,
    setApiKey,
    clearApiKey,
    hasApiKey,
    getModel,
    setModel,
    isEnabled,
    setEnabled,
    testConnection,
    evaluate
  };
  
})(typeof window !== 'undefined' ? window : global);
